//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFT.Training.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostan
    {
        
        public Ostan()
        {
            this.Shahrs = new List<Shahr>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public  List<Shahr> Shahrs { get; set; }
    }
}
